### ISSUE TITLE
я уже говорил что это не работает

### ISSUE THREAD

**Issue by 10606** [Good-Morning/optimizative_jabas#2]
https://github.com/Good-Morning/optimizative_jabas/blame/master/mo/hw1/task3_visualize.ipynb
Q = sum_i(ln(1 + exp(-y[i] * <X[i], w>))) + lambda/2 * <w, w>

Q = <1, ln(1 + exp(-arg))(y @ X * w)> + lambda/2 * <w, w>

dQ/dw_k = sum_i(-y[i] * X[i][k] / (1 + exp(y[i] * <X[i], w>))) + lambda * w_k

dQ/dw = X^T * (y @ ((-1 / (1 + exp(arg)))(y @ (W * x)))) + lambda * w

ddQ/dw_k/dw_l = sum_i(exp(-y[i] * <X[i], w>) * X[i][k] * X[i][l] * y[i]^2 / (1 + exp(y[i] * <X[i], w>))^2) + ((k == l)? lambda : 0)
y = {-1, +1}

ddQ/dw/dw = X_T * diag((exp(arg) / (1 + exp(arg))^2)(y @ (X * w))) * X + lambda * diag(1)

_T - транспонирование
@ - произведение Адамара

**Comment by Good-Morning** [comment]
а шо это вообще?

**Comment by 10606** [comment]
> а шо это вообще?

3 номер

**Comment by Good-Morning** [comment]
это то, что уже написано у нас? 
Или что?

**Comment by 10606** [comment]
> это то, что уже написано у нас?
> Или что?

![image](https://user-images.githubusercontent.com/19792226/77251444-6f1bb080-6c5f-11ea-9de5-231f29e94ecb.png)
то что должно быть вместо этого

**Comment by 10606** [comment]
![2020-03-22_17-22](https://user-images.githubusercontent.com/19792226/77251756-472d4c80-6c61-11ea-97ff-8783e3ad50d2.png)
c пояснениями что откуда

**Comment by Good-Morning** [comment]
у нас все хорошо
не раскачивай лодку
